mkdir: cannot create directory ‘logs’: File exists
Loaded module: cuda/11.6
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type             | Params
---------------------------------------------
0 | network | Net              | 7.7 M 
1 | loss    | CrossEntropyLoss | 0     
---------------------------------------------
7.7 M     Trainable params
0         Non-trainable params
7.7 M     Total params
30.805    Total estimated model params size (MB)
/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:488: PossibleUserWarning: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test/predict dataloaders.
  rank_zero_warn(
/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    trainer.fit(model, train_dataloader, validation_dataloader)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/segmentation_model.py", line 47, in validation_step
    x_hat = self.network(x).flatten(start_dim=2).float()
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/Unet.py", line 165, in forward
    out_conv_1 = self.conv_11(x_img)        # Output size from this layer (254, 254, 64)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/zhome/8f/9/137455/Desktop/DeepLearningProject/venv_1/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (double) and bias type (float) should be the same
